## Pengantar Numpy
Numpy library (module) digunakan hampir semua komputasi numerik yang menggunakan Python. Numpy merupakan library yang menyediakan komputasi performa tinggi untuk komputasi data struktur vector, matrix, atau dimensi lainnya yang lebih tinggi di python. hal ini dikarenakan numpy diimplementasikan menggunakan bahasa C dan Fortran.

In [1]:
import numpy as np

Di library Numpy, array merupakan terminologi yang dipakai dalam menyebut Vektor, Matrik, atau dimensi lainnya 

### Membuat Numpy array

Terdapat beberapa cara untuk menginisialisasi numpy arrays, seperti:
- menggunakan Python list or tuples
- menggunakan fungsi yang didedikasikan untuk men-generete numpy array, seperti arange, linspace, dll
- mendapatakan data dari sebuah file

#### List Python => Numpy array
contoh membuat sebuah vektor ataupun matrik dari Python List.

In [2]:
# vektor = parameter masukan untuk fungsi numpy array adalah Python list
vektor = np.array([1,2,3,4])
vektor

array([1, 2, 3, 4])

In [3]:
# matrik: parameter masukan untuk fungsi numpy array adalah nested Python list
matriks = np.array([[1, 2], [3, 4]])
matriks

array([[1, 2],
       [3, 4]])

In [4]:
type(vektor), type(matriks)

(numpy.ndarray, numpy.ndarray)

In [5]:
vektor.shape

(4,)

In [6]:
matriks.shape

(2, 2)

In [7]:
vektor.size

4

In [8]:
matriks.size

4

In [9]:
np.shape(vektor)

(4,)

In [10]:
np.shape(matriks)

(2, 2)

In [11]:
np.size(vektor)

4

In [12]:
np.size(matriks)

4

terlihat sama kan? numpy array vs Python list. Kenapa tidak menggunakan Python list untuk komputsi daripada membuat type array baru menggunakan numpy?

Alasannya:
- Python list sangat umum. nilai dari list dapat berupa object apapun. Python list merupakan dynamically typed. tidak support fungsi matematika seperti perkalian matriks, pengimplementasian hal tersebut untuk Python list sangat tidak efisien karena masalah dynamic type
- Sedangkan numpy array merupakan statically typed dan homogen sehingga menjadikan numpy array memory efisien. type dari tiap element ditentukan saat numpy array dibuat. Dengan bertipe static type, implementasi untuk fungsi matematika seperti perkalian matriks dalam numpy array dapat dilakukan dengan cepat dikarenakan di compile dalam bahasa C dan Fortran.

In [13]:
matriks.dtype

dtype('int64')

In [14]:
vektor.dtype

dtype('int64')

In [15]:
matriks[0,0] ="tes"

ValueError: invalid literal for int() with base 10: 'tes'

cara mendefinisikan type data dari numpy array

In [16]:
matrik = np.array([[1, 2], [3, 4]], dtype=complex)

In [17]:
matrik

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

### function => numpy array

In [18]:
#parameter (awal, akhir, selisi)
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x= np.linspace(2, 3, 5)
x

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [20]:
# angka random dalam rentang[0,1] baris 5 kolomo 4
a =np.random.rand(5,4)
a

array([[ 0.57037241,  0.14370644,  0.63202619,  0.06359854],
       [ 0.08148054,  0.27364842,  0.25410734,  0.511016  ],
       [ 0.02443124,  0.28115443,  0.39890278,  0.49772728],
       [ 0.60923522,  0.94537921,  0.1825984 ,  0.23316685],
       [ 0.55579512,  0.80149749,  0.22779457,  0.73519471]])

In [21]:
# matrik diagonal
a =np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
a = np.zeros((3,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
a = np.ones((3,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### File I/O